apiVersion: apps/v1
kind: Deployment
metadata:
  name: top-secret
  labels:
    app: top-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top-secret
  template:
    metadata:
      labels:
        app: top-secret
    spec:
      containers:
      - name: main
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-files
          mountPath: "/usr/share/nginx/html"
          readOnly: true
      volumes:
        - name: secret-files
          secret:
            secretName: top-secret
            defaultMode: 0444
